version: "1.0"
type: component
data:
  name: omv-services-snapraid-settings-form-page
  type: formPage
  config:
    request:
      service: SnapRaid
      get:
        method: getSettings
      post:
        method: setSettings
    fields:
      - type: divider
        title: _("Settings")
      - type: numberInput
        name: blocksize
        label: _("Block size")
        value: 256
        validators:
          min: 0
          max: 65535
        hint: _("Block size in KiB")
      - type: numberInput
        name: hashsize
        label: _("Hash size")
        value: 16
        validators:
          min: 0
          max: 65535
        hint: _("Hash size in bytes")
      - type: numberInput
        name: autosave
        label: _("Auto save")
        value: 0
        validators:
          min: 0
          max: 65535
        hint: _("Automatically save the state when syncing after the specified amount of GiB is processed. Default value is 0, meaning disabled.")
      - type: numberInput
        name: percentscrub
        label: _("Scrub percentage")
        value: 12
        validators:
          min: 0
          max: 100
        hint: _("Scrub percentage used for scrub button on Drives tab.")
      - type: checkbox
        name: nohidden
        label: _("No hidden")
        value: false
        hint: _("Excludes hidden files and directories.")
      - type: select
        name: defaultarray
        label: _('Default array')
        textField: name
        valueField: uuid
        store:
          proxy:
            service: SnapRaid
            get:
              method: enumerateArrays
              params:
                addnone: true
        hint: _("Creates symlink from array config file to /etc/snapraid.conf allowing snapraid commands to work on default array without specifying the config file flag")
      - type: divider
        title: _("Diff script settings")
      - type: checkbox
        name: debug
        label: _("Debug")
        value: false
      - type: checkbox
        name: sendmail
        label: _("Send Mail notification")
        value: true
      - type: checkbox
        name: apprise
        label: _("Send Apprise notification")
        value: false
      - type: textInput
        name: apprisecmd
        label: _("Apprise URL or config argument.")
        hint: _("E.g. --config /myConfig.yml | gotifys://myHost/myToken | mailtos://userid:pass@domain.com;gotifys://myHost/myToken<br/>You can use multiple URLs, separate them with a ';'.")
        value: ""
        language: shell
        trim: true
        validators:
          pattern:
            pattern: "^(--config\\s\\/[^\"'\\s\\|\\&][^\"'\\n]+|[\\w]+?:\\/\\/[^\"'\\s\\|]+)$"
            errorData: _("The field is invalid, it can't contain quotes and the path to the config file and URL can't contain spaces. Path to config file must be full (start with '/').")
      - type: checkbox
        name: ntfy
        label: _("Send Ntfy notification")
        value: false
      - type: textInput
        name: ntfycmd
        label: _("Ntfy config command or host and/or topic. Report will be sent as an attachment.")
        hint: _("E.g. ntfy.local/myTopic | myTopic | --config /someConfig.yml")
        value: ""
        trim: true
        language: shell
        validators:
          pattern:
            pattern: "^(([\\w\\.]+\\/)?[-\\w]{1,64}|--config\\s\\/[^\"'\\s\\|\\&]+)$"
            errorData: _("The field can only contain a config command, a valid topic name or host and topic (don't add https:// at the start). No quotes or spaces are allowed. Path to config file must be full (start with '/').")
      - type: checkbox
        name: sendsnaplog
        label: _("Send SnapRAID command logs")
        value: true
        hint: _("Also send a compressed file with the SnapRAID commands (sync, diff, scrub) debug logs as attachment for Apprise and Ntfy notifications.")
      - type: checkbox
        name: sendnotifalways
        label: _("Always send notifications")
        value: false
        hint: _("Send notifications even if there are no data changes.")
      - type: checkbox
        name: runscrub
        label: _("Run scrub")
        value: true
        hint: _("Set to true if you want to scrub after a successful sync.")
      - type: checkbox
        name: prehash
        label: _("Pre-hash")
        value: true
        hint: _("Runs a preliminary hashing phase of all the new data to have an additional verification before the parity computation.")
      - type: checkbox
        name: runtouch
        label: _("Run touch if needed")
        value: false
        hint: _("Check array status and run touch if needed.")
      - type: numberInput
        name: scrubfreq
        label: _("Scrub frequency")
        value: 7
        validators:
          min: 0
          max: 365
        hint: _("Units in days.")
      - type: numberInput
        name: scrubpercent
        label: _("Scrub percentage")
        value: 100
        validators:
          min: 0
          max: 100
        hint: _("Scrub percentage used for diff script.")
      - type: numberInput
        name: updthreshold
        label: _("Update threshold")
        value: 0
        validators:
          min: 0
          max: 65535
        hint: _("Define threshold of updated files above which not to start the sync process. default = 0 to disable this check and always sync.")
      - type: numberInput
        name: delthreshold
        label: _("Delete threshold")
        value: 0
        validators:
          min: 0
          max: 65535
        hint: _("Define threshold of deleted files above which not to start the sync process. default = 0 to disable this check and always sync.")
    buttons:
      - template: submit
      - template: cancel
        execute:
          type: url
          url: "/services/snapraid"
      - text: _("Scheduled diff")
        execute:
          type: url
          url: "/services/snapraid/diff"
